# Site settings
title: 神奇的早起
SEOTitle: 早起 | 神奇的早起
header-img: img/home-bg.jpg
email: mjc1818@qq.com
description: "爱理财的程序员"
keyword: "程序员，量化，读书，早起，复盘"
url: "https://amazingmorning.github.io"
baseurl: ""



# SNS settings
RSS: false
wechat_username:     量化为生
github_username:     amazingmorning



# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
highlighter: rouge
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`



# Gems
# from PR#40, to support local preview for Jekyll 3.0
gems: [jekyll-paginate]



# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
kramdown:
  input: GFM                            # use Github Flavored Markdown !important



# Disqus settings
#disqus_username: _your_disqus_short_name_

# Duoshuo settings
duoshuo_username: huxblog
# Share component is depend on Comment so we can NOT use share only.
duoshuo_share: true                     # set to false if you want to use Comment without Sharing




# Analytics settings
# Baidu Analytics - 请自行申请后填写
# ba_track_id: your_baidu_track_id
# Google Analytics - 请自行申请后填写
# ga_track_id: 'UA-xxxxxx-xx'
# ga_domain: yourdomain.com



# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "一个程序员的日常，量化，投资，读书，早起，冥想，复盘等。"
sidebar-avatar: /img/avatar-hux.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`



# Featured Tags
featured-tags: true                     # whether or not using Feature-Tags
featured-condition-size: 1              # A tag will be featured if the size of it is more than this condition value



# Friends
friends: [
    {
        title: "Hux Blog",
        href: "http://huangxuan.me"
    },{
        title: "聚宽量化",
        href: "https://www.joinquant.com"
    },{
        title: "TradingView",
        href: "https://www.tradingview.com"
    },{
        title: "GitHub",
        href: "https://github.com"
    }
]
